framework:
    cache:
        app: app.cache_pool
        default_redis_provider: '%env(REDIS_URL)%'
        pools:
            app.cache_pool:
                adapter: cache.adapter.redis
                default_lifetime: 3600
